=== jbgross/dynamicmail/XML Manipulation/ObjectXmlUnitTests/ObjectXML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="ObjectXML" targetNamespace="ObjectXml" elementFormDefault="qualified" xmlns="ObjectXml" xmlns:mstns="ObjectXml" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">
  <xs:element name="SavedObjects" type="SavedObjectsType" />
  <xs:complexType name="SavedObjectsType">
    <xs:sequence maxOccurs="unbounded">
      <xs:element name="Object" type="ObjectType" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ObjectType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Primitive" type="PrimitiveType" />
      <xs:element name="Reference" type="ReferenceType" />
    </xs:choice>
    <xs:attribute name="Class" use="required" type="xs:string" />
    <xs:attribute name="ObjectID" use="required" type="xs:int" />
    <xs:attribute name="RootObject" type="xs:boolean" />
  </xs:complexType>
  <xs:complexType name="PrimitiveType">
    <xs:attribute name="VariableName" use="required" type="xs:string" />
    <xs:attribute name="Value" use="required" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ReferenceType">
    <xs:attribute name="VariableName" use="required" type="xs:string" />
    <xs:attribute name="ObjectID" use="required" type="xs:int" />
  </xs:complexType>
</xs:schema>

=== jbgross/dynamicmail/DynamicMailCombined/ObjectXmlUnitTests/ValidRead.xml
<?xml version="1.0" encoding="utf-8" ?>
<SavedObjects xmlns="ObjectXml" 
              xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="ObjectXml ObjectXML.xsd">
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="true" ObjectID="1">
    <Primitive VariableName="A" Value="1"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="4.5"/>
    <Primitive VariableName="E" Value="6.7"/>
    <Primitive VariableName="F" Value="h"/>
    <Primitive VariableName="G" Value="ijklmnop"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="2">
    <Primitive VariableName="A" Value="2"/>
    <Primitive VariableName="B" Value="3"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="5.6"/>
    <Primitive VariableName="E" Value="7.8"/>
    <Primitive VariableName="F" Value="d"/>
    <Primitive VariableName="G" Value="sub1"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="3">
    <Primitive VariableName="A" Value="6"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="9.5"/>
    <Primitive VariableName="E" Value="6.3"/>
    <Primitive VariableName="F" Value="k"/>
    <Primitive VariableName="G" Value="sub2"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="4">
    <Primitive VariableName="A" Value="8"/>
    <Primitive VariableName="B" Value="1"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="4.8"/>
    <Primitive VariableName="E" Value="1.7"/>
    <Primitive VariableName="F" Value="o"/>
    <Primitive VariableName="G" Value="sub3"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="5">
    <Primitive VariableName="A" Value="0"/>
    <Primitive VariableName="B" Value="5"/>
    <Primitive VariableName="C" Value="2"/>
    <Primitive VariableName="D" Value="73.5"/>
    <Primitive VariableName="E" Value="6.824"/>
    <Primitive VariableName="F" Value="e"/>
    <Primitive VariableName="G" Value="sub4"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject2, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="true" ObjectID="6">
    <Reference VariableName="A" ObjectID="2"/>
    <Reference VariableName="B" ObjectID="3"/>
    <Reference VariableName="C" ObjectID="4"/>
    <Reference VariableName="D" ObjectID="5"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="7">
    <Primitive VariableName="A" Value="2"/>
    <Primitive VariableName="B" Value="3"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="5.6"/>
    <Primitive VariableName="E" Value="7.8"/>
    <Primitive VariableName="F" Value="d"/>
    <Primitive VariableName="G" Value="sub5"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="8">
    <Primitive VariableName="A" Value="6"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="9.5"/>
    <Primitive VariableName="E" Value="6.3"/>
    <Primitive VariableName="F" Value="k"/>
    <Primitive VariableName="G" Value="sub6"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="9">
    <Primitive VariableName="A" Value="8"/>
    <Primitive VariableName="B" Value="1"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="4.8"/>
    <Primitive VariableName="E" Value="1.7"/>
    <Primitive VariableName="F" Value="o"/>
    <Primitive VariableName="G" Value="sub7"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="10">
    <Primitive VariableName="A" Value="0"/>
    <Primitive VariableName="B" Value="5"/>
    <Primitive VariableName="C" Value="2"/>
    <Primitive VariableName="D" Value="73.5"/>
    <Primitive VariableName="E" Value="6.824"/>
    <Primitive VariableName="F" Value="e"/>
    <Primitive VariableName="G" Value="sub8"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject2, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="11">
    <Reference VariableName="A" ObjectID="7"/>
    <Reference VariableName="B" ObjectID="8"/>
    <Reference VariableName="C" ObjectID="9"/>
    <Reference VariableName="D" ObjectID="10"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="12">
    <Primitive VariableName="A" Value="2"/>
    <Primitive VariableName="B" Value="3"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="5.6"/>
    <Primitive VariableName="E" Value="7.8"/>
    <Primitive VariableName="F" Value="d"/>
    <Primitive VariableName="G" Value="sub9"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject1, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="13">
    <Primitive VariableName="A" Value="6"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="9.5"/>
    <Primitive VariableName="E" Value="6.3"/>
    <Primitive VariableName="F" Value="k"/>
    <Primitive VariableName="G" Value="sub10"/>
  </Object>
  <Object Class="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject2, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject="false" ObjectID="16">
    <Reference VariableName="A" ObjectID="8"/>
    <Reference VariableName="B" ObjectID="13"/>
    <Reference VariableName="C" ObjectID="9"/>
    <Reference VariableName="D" ObjectID="12"/>
  </Object>
  <Object Class ="Edu.Psu.Ist.DynamicMail.UnitTests.TestObject3, Edu.Psu.Ist.DynamicMail.UnitTests" RootObject ="true" ObjectID ="17">
    <Primitive VariableName="A" Value="132"/>
    <Primitive VariableName ="B" Value="56.954"/>
    <Primitive VariableName="C" Value ="Something"/>
    <Reference VariableName="D" ObjectID="11"/>
    <Reference VariableName="E" ObjectID="16"/>
    <Reference VariableName="F" ObjectID="12"/>
    <Reference VariableName="G" ObjectID="7"/>
  </Object>
</SavedObjects>

=== jbgross/dynamicmail/XML Manipulation/ObjectXmlUnitTests/InvalidRead.xml
<?xml version="1.0" encoding="utf-8" ?>
<SavedObjects xmlns="ObjectXml"
              xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="ObjectXml ObjectXML.xsd">
  <Object Class="ObjectXmlUnitTests.TestObject1, ObjectXmlUnitTests" RootObject="true" ObjectID="1">
    <Primitive VariableName="A" Value="1"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="4.5"/>
    <Primitive VariableName="E" Value="6.7"/>
    <Primitive VariableName="F" Value="h"/>
    <Primitive VariableName="G" Value="ijklmnop"/>
  </Object>
  <Object Class="ObjectXmlUnitTests.TestObject1, ObjectXmlUnitTests" RootObject="false" ObjectID="2">
    <Primitive VariableName="A" Value="2"/>
    <Primitive VariableName="B" Value="3"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="5.6"/>
    <Primitive VariableName="E" Value="7.8"/>
    <Primitive VariableName="F" Value="d"/>
    <Primitive VariableName="G" Value="sub1"/>
  </Object>
  <Object Class="ObjectXmlUnitTests.TestObject2, ObjectXmlUnitTests" RootObject="true" ObjectID="6">
    <Reference VariableName="A" ObjectID="2"/>
    <Reference VariableName="B" ObjectID="3"/>
    <Reference VariableName="C" ObjectID="4"/>
    <Reference VariableName="D" ObjectID="5"/>
  </Object>
  <Object Class="ObjectXmlUnitTests.TestObject1, ObjectXmlUnitTests" RootObject="false" ObjectID="3">
    <Primitive VariableName="A" Value="6"/>
    <Primitive VariableName="B" Value="2"/>
    <Primitive VariableName="C" Value="3"/>
    <Primitive VariableName="D" Value="9.5"/>
    <Primitive VariableName="E" Value="6.3"/>
    <Primitive VariableName="F" Value="k"/>
    <Primitive VariableName="G" Value="sub2"/>
  </Object>
  <Object Class="ObjectXmlUnitTests.TestObject1, ObjectXmlUnitTests" RootObject="false" ObjectID="4">
    <Primitive VariableName="A" Value="8"/>
    <Primitive VariableName="B" Value="1"/>
    <Primitive VariableName="C" Value="4"/>
    <Primitive VariableName="D" Value="4.8"/>
    <Primitive VariableName="E" Value="1.7"/>
    <Primitive VariableName="F" Value="o"/>
    <Primitive VariableName="G" Value="sub3"/>
  </Object>
  <Object Class="ObjectXmlUnitTests.TestObject1, ObjectXmlUnitTests" RootObject="false" ObjectID="5">
    <Primitive VariableName="A" Value="0"/>
    <Primitive VariableName="B" Value="5"/>
    <Primitive VariableName="C" Value="2"/>
    <Primitive VariableName="D" Value="73.5"/>
    <Primitive VariableName="E" Value="6.824"/>
    <Primitive VariableName="F" Value="e"/>
    <Primitive VariableName="G" Value="sub4"/>
  </Object>
</SavedObjects>
